### ISSUE TITLE
Add a starter template

### ISSUE THREAD

**Issue by cedricatoutliant** [contentful/experience-builder#548]
Adding a starter template would really help as some things are unclear and documentation is lacking information. 
A start demo or skeleton would help to clarify more than a written documentation can ever do.

**Comment by elylucas** [comment]
Thanks for the feedback @cedricatoutliant. We are starting to think about what this will look like and are planning on doing it sometime in the future.

**Comment by primeinteger** [comment]
Hey @cedricatoutliant, we have added additional Examples and Template apps into this repo that you can use as a starter template or reference. Please take a look when you have some time and let us know if anything that we can add to improve these apps!
- [Examples](https://github.com/contentful/experience-builder/tree/development/examples)
- [Templates](https://github.com/contentful/experience-builder/tree/development/packages/templates)
