### ISSUE TITLE
Nested component categories

### ISSUE THREAD

**Issue by samiresua** [contentful/experience-builder#553]
Would be very useful for organising components into  intuitive buckets.

For example:

```ts
definition:  {
   category: 'Containers/Scroller'
}
```

**Comment by ryunsong-contentful** [comment]
Thank you for the feedback, taking it back to the team!

**Comment by primeinteger** [comment]
We already have this feature, that's exactly what the `category` property does in the component definition. See: https://www.contentful.com/developers/docs/experiences/component-definition-schema/

The value you use for your `category` in the component definition is used to organized components into different Folders in the Studio Canvas editor.

I'll close this issue, but let us know if you have other questions.

**Comment by sami616** [comment]
Sorry im specifically calling out the ability to nest folders with a slash. Is this currently supported?
