### ISSUE TITLE
Rename layers w\ search

### ISSUE THREAD

**Issue by samiresua** [contentful/experience-builder#565]
Are there plans to be able to rename layers? I can see having more contextual, meaningful layer names would help a lot for complex experiences with lots of things on the canvas.

**Comment by ryunsong-contentful** [comment]
Yes, we have received feedback about this issue as well and have prioritized the work accordingly

**Comment by chasepoirier** [comment]
Hi @samiresua, as of version `1.3.0` we now support layer renaming 🚀

**Comment by samiresua** [comment]
yes i noticed! thank you!
