### ISSUE TITLE
Hover states for containers

### ISSUE THREAD

**Issue by samiresua** [contentful/experience-builder#566]
Containers are able to be hyperlinked essentially making them `<a>` tags, however it doesnt seem  possible to add any :active,  :hover state styles for these when a link is present. Are there any plans to let authors update things like colours, shadows, opacity, border to reflect these pseudo states?

**Comment by ryunsong-contentful** [comment]
Hey samireusa, really appreciate the feedback. I will take this back to the team and prioritize accordingly

**Comment by elylucas** [comment]
Hi @samiresua, for now, we are advising that you can add your own css to your page/component to handle additional states in your app. We might visit adding more advanced styling choices later on.
